project:
  type: website
  output-dir: docs
  
execute:
  cache: true
  freeze: auto

website:
  reader-mode: true
  page-navigation: true
  title: "**Rosa, R. B.**"
  navbar:
    pinned: true
    border: false
    background: "light"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Mestrado"
        menu:
          - text: "FIP606 - Projeto Final"
            file: script.qmd
       
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/raphaelfitopatologia
      - icon: instagram
        href: https://www.instagram.com/invites/contact/?i=xk2vhn0e4rad&utm_content=2owlczy
      - icon: github
        menu:
          - text: Código fonte
            url:  https://github.com/rb-rosa
          - text: Reportar erro
            url:  mailto:rbarboza.rosa@gmail.com
  
  page-footer:
    border: true
    left: "Copyright 2023, Raphael B Rosa"
format:
  html:
    theme: 
      light: default
      dark: cyborg
      
    css: styles.css
    toc: true
editor: visual

  

